/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:d500fef3-6b35-4795-bf1f-0dd1432ae69f",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_9VqrXqF5P",
    "aws_user_pools_web_client_id": "5tsur1ersi3fk63drlhb6u12ls",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://6ypekix2rbht7dymy7xkcxnope.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-p7bsybxr6zhyvjgrcrqokts2fe",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://1mcgljvh5i.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ],
    "aws_user_files_s3_bucket": "amplifyapp2d0f4df7e70a4c4ea261b5f48f3d5bd0201631-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
