/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:d500fef3-6b35-4795-bf1f-0dd1432ae69f",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_9VqrXqF5P",
    "aws_user_pools_web_client_id": "5tsur1ersi3fk63drlhb6u12ls",
    "oauth": {}
};


export default awsmobile;
